### ISSUE TITLE
/proc/acpi/button/lid/ may contain only LID rather than LID0

### ISSUE THREAD

**Issue by ao5357** [pop-os/hidpi-daemon#11]
https://github.com/pop-os/hidpi-daemon/blob/154fa68c9f6b50bd96ae213c544437ccc2e11d88/hidpidaemon/hidpidaemon2.py#L1032

On my ASUS VivoBook S510UN-EH76 with POP! OS, doing an `ls /proc/acpi/button/lid/` yields only `LID` rather than the `LID0` that the HiDPI daemon looks for. This results in numerous writes to the syslog, and may contribute to the issues I've encountered with closing my laptop's lid.

**Comment by djordan2** [comment]
Thanks for the report.  The daemon should probably handle different LID file names and not report error messages when it doesn't find one any more.  I'm glad you did notice the error messages though and report on your specific hardware.

**Comment by djordan2** [comment]
@ao5357 This should be fixed in the latest release.  Please run updates and let us know if it works for you.

**Comment by ao5357** [comment]
@djordan2 I can confirm that the log messages no longer appear when I close and re-open the lid. Thank you very much!
