### ISSUE TITLE
20.04: Nvidia 440.64 and external displays

### ISSUE THREAD

**Issue by leviport** [pop-os/hidpi-daemon#29]
While testing 440.64 on the addw1 running 20.04, external displays were not behaving great until I deactivated the HiDPI daemon. I did not investigate further, but I can add more details to this issue once I get a chance to look into it more.

**Comment by rhb388** [comment]
I'm having this same issue on XPS 7590 with 440.82 running 20.04.  Very sluggish until HiDPI daemon is deactivated.
