### ISSUE TITLE
Display resetting to defaults after sleep/reboot

### ISSUE THREAD

**Issue by briggs1978** [pop-os/hidpi-daemon#5]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please start a conversation in our chat https://chat.pop-os.org/ or post on our subreddit https://reddit.com/r/pop_os - as these are the proper forums for those types of posts.

**IMPORTANT**
Please attach output of the xrandr command and ~.config/montors.xml to help diagnose the issue.
>
xrandr
Screen 0: minimum 320 x 200, current 3200 x 1800, maximum 8192 x 8192
eDP-1 connected primary 3200x1800+0+0 (normal left inverted right x axis y axis) 294mm x 165mm
   3200x1800     59.98*+  59.96    59.94    47.99  
   2880x1620     59.96    59.97  
   2560x1600     59.99    59.97  
   2560x1440     59.99    59.99    59.96    59.95  
   2048x1536     60.00  
   1920x1440     60.00  
   1856x1392     60.01  
   1792x1344     60.01  
   2048x1152     59.99    59.98    59.90    59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01    59.97    59.96    59.93  
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)

>
<monitors version="2">
  <configuration>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>eDP-1</connector>
          <vendor>SHP</vendor>
          <product>0x144a</product>
          <serial>0x00000000</serial>
        </monitorspec>
        <mode>
          <width>1600</width>
          <height>900</height>
          <rate>119.97659301757812</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
  <configuration>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>DP-1-1</connector>
          <vendor>SAM</vendor>
          <product>S24E348</product>
          <serial>0x5a5a5035</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>302</x>
      <y>1080</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>eDP-1</connector>
          <vendor>SHP</vendor>
          <product>0x144a</product>
          <serial>0x00000000</serial>
        </monitorspec>
        <mode>
          <width>1360</width>
          <height>768</height>
          <rate>59.960025787353516</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
  <configuration>
    <logicalmonitor>
      <x>153</x>
      <y>1080</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>eDP-1</connector>
          <vendor>SHP</vendor>
          <product>0x144a</product>
          <serial>0x00000000</serial>
        </monitorspec>
        <mode>
          <width>1600</width>
          <height>900</height>
          <rate>119.97659301757812</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>DVI-I-1-1</connector>
          <vendor>VSC</vendor>
          <product>VG2439 Series</product>
          <serial>UBX162320519</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
</monitors>

 **Distribution - (run ```cat /etc/os-release```)**
>
cat /etc/os-release
NAME="Pop!_OS"
VERSION="18.04 LTS (Testing)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS (Testing)"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 
 **Related Application and/or Package Version - (run ```apt policy $PACKAGE NAME```)**

**Issue/Bug Description**
Since a recent update, my display keeps reverting back to defaults when I resume from sleep.
When this happens, I now get a "high dpi" notification at the top.  The default setting is 3200x1800 @ 200%, but what I prefer to have it set at is 1600x900 @ 100%.
A redditer told me to uninstall the highdpi daemon and that worked, but another update seems to have reinstalled it. 

**Steps to reproduce (if you know)**

**Expected behavior**

**Other Notes**

**Comment by briggs1978** [comment]
Just to clarify, the current pattern is that if I reboot the computer, it resets to full resolution, high dpi.  Today I've just been leaving it like that since I haven't been docking.  Once the computer goes to sleep though, it has been setting itself back to 1600x900 @ 100%.   I wouldn't notice this at all, since it looks identical, but many applications don't handle the sudden change very well, so I'm left with a huge pointer, and huge title bars in some apps.

Lots of fun.  I think until further notice, I'm going to uninstall the daemon.

**Comment by jasonmccallister** [comment]
This is still an issue and has been reported here: https://github.com/pop-os/pop/issues/214
