### ISSUE TITLE
Unhandled Exception in hidpi-notification script notification_closed method

### ISSUE THREAD

**Issue by danieljohnson2** [pop-os/hidpi-daemon#6]
**IMPORTANT**
Please attach output of the xrandr command and ~.config/montors.xml to help diagnose the issue.
[monitors.xml.txt](https://github.com/pop-os/hidpi-daemon/files/1934328/monitors.xml.txt)
[xrandr.txt](https://github.com/pop-os/hidpi-daemon/files/1934327/xrandr.txt)

 **Distribution - (run ```cat /etc/os-release```)**
 NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
 
 **Related Application and/or Package Version - (run ```apt policy $PACKAGE NAME```)**

'apt policy hidpi-daemon' output:
hidpi-daemon:
  Installed: 17.10.2+1523581212+17.10~78f43b3
  Candidate: 17.10.2+1523581212+17.10~78f43b3
  Version table:
 *** 17.10.2+1523581212+17.10~78f43b3 500
        500 http://ppa.launchpad.net/system76-dev/stable/ubuntu artful/main amd64 Packages
        500 http://ppa.launchpad.net/system76-dev/stable/ubuntu artful/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description**
I get crash reports after booting on Ubuntu with gnome-session installed. It looks like the service com.system76.hidpi is not yet available during bootup and and exception is raised in the /usr/lib/hidpi-notification script, notification_closed function.

This function appears to do nothing useful (it reads some data into local variables, then exits). The error can be contained by adding "try:" and "except: pass" around the body of this function. It still does nothing useful, but this seems to silence the crash.

**Steps to reproduce (if you know)**
It happens on each reboot. Reboot, log-in, and wait a few seconds (not more than a minute) and a Ubuntu crash reporting dialog comes up.

I don't know for sure, but I suspect you may need to have gnome-session installed to trigger this.

I am seeing this issue on two machines (the other is a Kudu laptop), but both have gnome-session.

I'm not running Pop_OS!, and my machines all predate it, but this appears to be the software the System 76 ppa provides to everyone.

Here's the apport crash report file:
[_usr_lib_hidpi-daemon_hidpi-notification.1000.crash.txt](https://github.com/pop-os/hidpi-daemon/files/1934343/_usr_lib_hidpi-daemon_hidpi-notification.1000.crash.txt)

There's a traceback in there, check it out!

**Expected behavior**
This system has just one monitor, and it is lodpi at that. This program should not do anything at all.

**Other Notes**
It might be nice to be able to uninstall just hidpi-daemon and not any other system76 software. HiDPI is cool and all, but not everybody has it.

**Comment by skepickle** [comment]
+1

**Comment by djordan2** [comment]
Thanks for the report, I'm changing the notification process to check that the dbus interface is available before using it.  

As for your other notes, the hidpi daemon should do nothing unless you have connected HiDPI displays, but can be useful if you ever do.  If you want, you should be able to uninstall it without removing the system76 driver.  In Pop!_OS 18.04, it can be turned off in the Displays tab in Gnome Control Center whenever you want. On other distributions, use `gsettings set com.system76.hidpi enable false`
