### ISSUE TITLE
First notification upon logging in is backwards

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/hidpi-daemon#9]
Up-to-date Pop!_OS 18.04 on the galp2. Intel, 13.3" 3200×1800 internal display, 27" 2560×1440 external display above.

![image](https://user-images.githubusercontent.com/611168/40439616-aaa82a8a-5e78-11e8-8b22-47a6c077877a.png)

When I boot into Pop!_OS and log in with the external display connected, I get a notification saying the displays are in "Native Mode", although they're actually in Optimized Mode. Clicking the notification the first time does nothing, then correctly throws the "Displays Set to Optimized Mode" notification

**Comment by cassidyjames** [comment]
This actually looks like the notification just always defaults to the wrong thing on Intel. When booting with no external displays, the notification first says that displays were set to LoDPI mode even though it's in HiDPI. Then clicking the notification similarly corrects the state.

**Comment by djordan2** [comment]
Fixed in 18.04.4
